name: Aquarium Data Sync

on:
  schedule:
    # Запуск кожні 30 хвилин (*/30)
    - cron: '*/30 * * * *'
  # Додає кнопку для ручного запуску (щоб перевірити)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          TUYA_ACCESS_ID: ${{ secrets.TUYA_ACCESS_ID }}
          TUYA_ACCESS_KEY: ${{ secrets.TUYA_ACCESS_KEY }}
          TUYA_DEVICE_ID: ${{ secrets.TUYA_DEVICE_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python collect_tuya_supabase.py
